version: "3.4"

services:
  nginx:
    image: nginx:1.14.0
    container_name: ticketbase_nginx
    restart: on-failure

  ticketbase:
    image: ticketbase
    build:
      context: .
      target: application
    container_name: ticketbase_app