version: "3.4"

services:
  nginx:
    image: nginx:1.14.0
    ports:
      - "8000:80"
    volumes:
      - "./conf/nginx_development.conf:/etc/nginx/conf.d/default.conf"
    restart: unless-stopped

  ticketbase:
    image: ticketbase
    build:
      context: .
      target: application
    volumes:
      - ".:/ticketbase"
      - ".data/root:/root"
    environment:
      - DJANGO_SETTINGS_MODULE=ticketbase.settings.development
      - DJANGO_SU_NAME=admin
      - DJANGO_SU_EMAIL=admin@example.com
      - DJANGO_SU_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    restart: unless-stopped
    tty: true
    depends_on:
      - postgres
    ports:
        - "8001:8000"

  postgres:
    image: mdillon/postgis:11
    environment:
      - POSTGRES_DB=ticketbase
      - POSTGRES_USER=ticketbase
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ".data/db:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --quiet || exit 1"]
      interval: 1m
      timeout: 30s
      retries: 10
      start_period: 40s

    container_name: ticketbase_postgres
    restart: unless-stopped
