# Generated by Django 2.2.4 on 2019-09-22 06:31

from django.db import migrations, models
import django_fixes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_fixes.BetterImageField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.FloatField(null=True)),
            ],
        ),
    ]
