# Generated by Django 2.2.4 on 2019-09-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0003_auto_20190927_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
