# Generated by Django 2.2.4 on 2019-09-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0004_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_closed',
            field=models.BooleanField(default=True),
        ),
    ]
