# Generated by Django 2.2.4 on 2019-09-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0006_auto_20190927_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.TextField(null=True),
        ),
    ]
