# Generated by Django 2.2.4 on 2019-09-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codebase_id',
            field=models.IntegerField(null=True),
        ),
    ]
